defaults:
  - model: lcnn
  - writer: cometml
  - metrics: eer
  - datasets: asvspoof
  - dataloader: asvspoof
  - transforms: none
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 1 # will be replaced in train.py
loss_function:
  _target_: src.loss.bce_with_logits_loss.BCEWithLogitsLossWrapper
  pos_weight: [8.837]
trainer:
  log_step: 300
  n_epochs: 20
  epoch_len: null # null (it means epoch_len = len(dataloader)) or cnt of batches we want to be on the epoch
  save_dir: "saved/"
  save_period: 100 # checkpoint each save_period epochs in addition to the best epoch
  monitor: "min eval_EER" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  early_stop: 10 # epochs for early stopping
  device_tensors: ["audio", "label"] # which tensors should be on device (ex. GPU), keys from Dataset
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  seed: 10
  train_one_batch: False
