defaults:
  - model: lcnn
  - metrics: eer
  - datasets: asvspoof_eval # we do not want to run inference on training data
  - dataloader: asvspoof
  - transforms: none
  - _self_
inferencer:
  device_tensors: ["audio", "label"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference" # any name here, can be a dataset name
  seed: 10
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
